Modernize and update metadata for rustls fork
rustls/webpki pull request #1
Opened 2022-08-31 09:47 UTC by djc

2022-09-01 22:25 UTC, jsha requested changes
In https://github.com/rustls/webpki/pull/1/commits/ef0c3d388dade898b21af7999e3386a6ae3ea8d2 you say Ubuntu 18 is deprecated. By whom? According to https://ubuntu.com/about/release-cycle it's supported by Ubuntu until April 2023. It's fine to drop support in this crate, but probably we should document that; or follow the example of \*ring\* and just document what platforms we test on rather than committing to supporting specific platforms.

2022-09-02 10:28 UTC, djc commented
Sorry, yes, 18.04 is specifically deprecated for GitHub Actions:

https://github.blog/changelog/2022-08-09-github-actions-the-ubuntu-18-04-actions-runner-image-is-being-deprecated-and-will-be-removed-by-12-1-22/

2022-09-02 10:39 UTC, djc commented on .github/workflows/ci.yml
> +      - uses: actions-rs/toolchain@v1
Maybe, but then we should also do that across the other repos in the rustls org? It feels like a big job and it's not obvious to me that there are big risks here.

So my take is that for now, Brian's forks are probably less- or equally well maintained compared to the originals (and there are currently no secrets in this repository, either).

2022-09-02 16:41 UTC, jsha approved these changes
Sounds good. 👍🏻

2022-09-02 19:28 UTC, merged

2022-09-02 19:48 UTC, ctz commented on .github/workflows/ci.yml
> +      - uses: actions-rs/toolchain@v1
Seems like there are two options for dealing with GH actions poor security defaults:

1. totally distrust the CI process: it gets read-only access to the repo (same as anything else on the internet), and no special access to secrets etc
2. carefully curate and control the CI process, so we can trust it with secrets and privileged repo access

I think we should be expending effort doing (1) -- and I've just checked this repo has minimal GITHUB_TOKEN permissions (which should be the case for the other rustls-org repos already)